/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobuku;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LEGION5
 */
public class penjualan extends javax.swing.JFrame {

    public penjualan() {
        initComponents();
        tatok.setVisible(true);
        tombolHidden();
        hidden();
    }
    private void siapIsi(boolean a){
        jumlah.setEnabled(a);
        nonota.setEnabled(a);
        kdbuku.setEnabled(a);
        judulbuku.setEnabled(a);
        hargajual.setEnabled(a);
    }

    private void bersih(){
        jumlah.setText(null);
        nonota.setText(null);
        nmpembeli.setText(null);
        kdbuku.setText(null);
        judulbuku.setText(null);
        hargajual.setText(null);
        jumlah.setText(null);
        ttotal.setText("0");
        ttunai.setText("0");
        tKembali.setText("0");
    }
    public void hidden(){
        nonota.setEnabled(false);
        kdbuku.setEnabled(false);
        judulbuku.setEnabled(false);
        hargajual.setEnabled(false);
        
    }
    private void tampiltanggal(){
        DateFormat tgl = new SimpleDateFormat("dd/MMMM/yyyy");
        String htgl = tgl.format(Calendar.getInstance().getTime());
        tanggal.setText(htgl);
    }
    private void buatNoNota(){
         ListDb = bc.tampil();
        if(ListDb.isEmpty()){
            nonota.setText("N-"+1);
        }else{
            int a=ListDb.size()-1;
            int no=Integer.parseInt(ListDb.get(a).getNota().replace("N-", ""))+1;
            nonota.setText("No-"+no);
            nonota.setEnabled(false);
        }
    }
    public void tombolHidden(){
        btnTambah.setEnabled(false);
        btnKurang.setEnabled(false);
        tanggal.setEnabled(false);
    }
    public void tombolNormal(){
        btnTambah.setEnabled(false);
        btnKurang.setEnabled(false);
    }
    private void buatTabelModel(){
        model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("Judul");
        model.addColumn("Genre");
        model.addColumn("Penulis");
        model.addColumn("Harga");
        model.addColumn("Stok");
        jTable2.setModel(model);
    }
    private void tampilbuku(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListBuku.clear();
        ListBuku = ob.tampil();
        for(int x=0;x<ListBuku.size();x++){
            Object[] data = new Object[6];
            data[0]= ListBuku.get(x).getId();
            data[1]= ListBuku.get(x).getJDL();
            data[2]= ListBuku.get(x).getGenre();
            data[3]= ListBuku.get(x).getPenulis();
            data[4]= ListBuku.get(x).getHarga();
            data[5]= ListBuku.get(x).getStok();
            model.addRow(data);
        }   
    }
    private void buatTableBeli(){
        model = new DefaultTableModel();
        model.addColumn("ID Buku");
        model.addColumn("Judul");
        model.addColumn("Harga");
        model.addColumn("Jumlah");
        model.addColumn("Total");
        jTable1.setModel(model);
    }
    private void tampilbeli(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListDPJ.clear();
        ListDPJ = pc.CariBuku(nonota.getText());
        for(int x=0;x < ListDPJ.size();x++){
            Object[] data = new Object[5];
            data[0]= ListDPJ.get(x).getIDBK();
            data[1]= ListDPJ.get(x).getJudul();
            data[2]= ListDPJ.get(x).getHargaJ();
            data[3]= ListDPJ.get(x).getJumlahB();
            data[4]= ListDPJ.get(x).getTotalB();
            model.addRow(data);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ttunai = new javax.swing.JTextField();
        tKembali = new javax.swing.JTextField();
        ttotal = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnKurang = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tatok = new javax.swing.JTextField();
        nonota = new javax.swing.JTextField();
        nmpembeli = new javax.swing.JTextField();
        judulbuku = new javax.swing.JTextField();
        kdbuku = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        hargajual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nmbuku = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btntambahbuku = new javax.swing.JButton();
        btnpilih = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        tanggal = new javax.swing.JTextField();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(44, 62, 80));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cari Data Buku");

        txtcari.setBackground(new java.awt.Color(44, 62, 80));
        txtcari.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtcari.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcari, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37))
        );

        jDialog1.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 580, 310));

        jPanel5.setBackground(new java.awt.Color(170, 0, 0));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Data Buku");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialog1.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transaksi Penjualan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 70));

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Kembali");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Tunai");

        ttunai.setBackground(new java.awt.Color(44, 62, 80));
        ttunai.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ttunai.setForeground(new java.awt.Color(255, 255, 255));
        ttunai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ttunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttunaiActionPerformed(evt);
            }
        });
        ttunai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ttunaiKeyPressed(evt);
            }
        });

        tKembali.setBackground(new java.awt.Color(44, 62, 80));
        tKembali.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tKembali.setForeground(new java.awt.Color(255, 255, 255));
        tKembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKembaliActionPerformed(evt);
            }
        });

        ttotal.setBackground(new java.awt.Color(44, 62, 80));
        ttotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ttotal.setForeground(new java.awt.Color(255, 255, 255));
        ttotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttotalActionPerformed(evt);
            }
        });

        btnTambah.setText("+");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnKurang.setText("-");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Total");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnKurang))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ttunai, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 140, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKurang)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ttunai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setText("NO Nota");

        tatok.setBackground(new java.awt.Color(255, 153, 153));
        tatok.setBorder(null);
        tatok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatokActionPerformed(evt);
            }
        });

        nonota.setBackground(new java.awt.Color(44, 62, 80));
        nonota.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nonota.setForeground(new java.awt.Color(255, 255, 255));
        nonota.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nonota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonotaActionPerformed(evt);
            }
        });

        nmpembeli.setBackground(new java.awt.Color(44, 62, 80));
        nmpembeli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nmpembeli.setForeground(new java.awt.Color(255, 255, 255));
        nmpembeli.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nmpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmpembeliActionPerformed(evt);
            }
        });

        judulbuku.setBackground(new java.awt.Color(44, 62, 80));
        judulbuku.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        judulbuku.setForeground(new java.awt.Color(255, 255, 255));
        judulbuku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        judulbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulbukuActionPerformed(evt);
            }
        });

        kdbuku.setBackground(new java.awt.Color(44, 62, 80));
        kdbuku.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kdbuku.setForeground(new java.awt.Color(255, 255, 255));
        kdbuku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        kdbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kdbukuActionPerformed(evt);
            }
        });

        jumlah.setBackground(new java.awt.Color(44, 62, 80));
        jumlah.setForeground(new java.awt.Color(255, 255, 255));
        jumlah.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        hargajual.setBackground(new java.awt.Color(44, 62, 80));
        hargajual.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        hargajual.setForeground(new java.awt.Color(255, 255, 255));
        hargajual.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        hargajual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargajualActionPerformed(evt);
            }
        });

        jLabel7.setText("Nama Pembeli");

        jLabel8.setText("ID Buku");

        nmbuku.setText("Judul Buku");

        jLabel10.setText("Harga");

        jLabel11.setText("Jumlah");

        jLabel12.setText("Tanggal Transaksi");

        btntambahbuku.setText("Tambah");
        btntambahbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahbukuActionPerformed(evt);
            }
        });

        btnpilih.setText("Pilih");
        btnpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihActionPerformed(evt);
            }
        });

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        tanggal.setBackground(new java.awt.Color(44, 62, 80));
        tanggal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(nmbuku)
                            .addComponent(jLabel8))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hargajual, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(judulbuku, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jumlah, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nonota, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tatok, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nmpembeli, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(kdbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnpilih))
                            .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btntambahbuku)
                        .addGap(18, 18, 18)
                        .addComponent(btnsimpan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nonota, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tatok, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nmpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kdbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btnpilih))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nmbuku))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntambahbuku)
                            .addComponent(btnsimpan))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 940, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ttunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttunaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttunaiActionPerformed

    private void tKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tKembaliActionPerformed

    private void ttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttotalActionPerformed

    private void tatokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tatokActionPerformed

    private void nonotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonotaActionPerformed

    private void nmpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmpembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmpembeliActionPerformed

    private void judulbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judulbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judulbukuActionPerformed

    private void kdbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kdbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kdbukuActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void hargajualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargajualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargajualActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcariActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    private void btntambahbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahbukuActionPerformed
        // TODO add your handling code here:
        if(btntambahbuku.getText().equalsIgnoreCase("Tambah")){
            btntambahbuku.setText("Batal");
            siapIsi(true);
            bersih();
            hidden();
            tampiltanggal();
            buatNoNota();
            nmpembeli.requestFocus();
            btnTambah.setEnabled(true);
            btnKurang.setEnabled(true);
            tanggal.setEnabled(false);
        }else{
            bersih();
            siapIsi(false);
            btntambahbuku.setText("Tambah");
            tombolNormal();
            bersih();
            nonota.setText(null);
            tanggal.setText(null);
        }
    }//GEN-LAST:event_btntambahbukuActionPerformed

    private void btnpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihActionPerformed
        // TODO add your handling code here:
        buatTabelModel();
        tampilbuku();
        txtcari.setText(null);
        jDialog1.setVisible(true);
        jDialog1.setBounds(300,300,472,390);
        txtcari.requestFocus();
    }//GEN-LAST:event_btnpilihActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int baris = jTable2.getSelectedRow();
        kdbuku.setText(jTable2.getModel().getValueAt(baris, 0).toString());
        judulbuku.setText(jTable2.getModel().getValueAt(baris, 1).toString());
        tatok.setText(jTable2.getModel().getValueAt(baris, 5).toString());
        hargajual.setText(jTable2.getModel().getValueAt(baris, 4).toString());
        jumlah.requestFocus();
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        // TODO add your handling code here:
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ListBuku.clear();
        ListBuku=ob.cariBuku(txtcari.getText());
        for(int x=0;x<ListBuku.size();x++){
            Object[] data = new Object[6];
            data[0]= ListBuku.get(x).getId();
            data[1]= ListBuku.get(x).getJDL();
            data[2]= ListBuku.get(x).getGenre();
            data[3]= ListBuku.get(x).getPenulis();
            data[4]= ListBuku.get(x).getHarga();
            data[5]= ListBuku.get(x).getStok();
            model.addRow(data);
        }
    }//GEN-LAST:event_txtcariKeyReleased

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if(kdbuku.getText().equalsIgnoreCase("")||nonota.getText().equalsIgnoreCase("")||judulbuku.getText().equalsIgnoreCase("")||nmpembeli.getText().equalsIgnoreCase("")
                ||hargajual.getText().equalsIgnoreCase("")||jumlah.getText().equalsIgnoreCase("")||ttotal.getText().equalsIgnoreCase("")||ttunai.getText().equalsIgnoreCase("")
                ||tKembali.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Data Harus Lengkap");
        }else{
         int jml=Integer.parseInt(jumlah.getText());
         int stok=Integer.parseInt(tatok.getText());
         if(jml>stok){
             JOptionPane.showMessageDialog(this, "Stok Buku Tidak Cukup!");
         }else{
             ListDb=pc.CekBuku(nmpembeli.getText(), kdbuku.getText());
             if(ListDb.size()>0){
                 JOptionPane.showMessageDialog(this, "Buku sudah di Beli");
             }else{
                 int harga = Integer.parseInt(hargajual.getText());
                 datapenjualan dp = new datapenjualan();
                 dp.setNonota(nonota.getText());
                 dp.setIDBK(kdbuku.getText());
                 dp.setJudul(judulbuku.getText());
                 dp.setHargaJ(harga);
                 dp.setJumlahB(jml);
                 dp.setTotalB(harga*jml);
                 if(pc.tambahpenjualan(dp) == 0){
                      JOptionPane.showMessageDialog(this, "Data gagal disimpan");
                 }else{
                     int sisaStok = stok-jml;
                     ob.updateStok(sisaStok,kdbuku.getText());
                     buatTableBeli();
                     tampilbeli();
                     int total = Integer.parseInt(ttotal.getText());
                     int totalbyr = total+(harga*jml);
                     ttotal.setText(Integer.toString(totalbyr));
                     JOptionPane.showMessageDialog(this, "Data Telah ditambahkan");
                     kdbuku.setText(null);
                     judulbuku.setText(null);
                     hargajual.setText(null);
                     jumlah.setText(null);
                     ttunai.setText("0");
                     tKembali.setText("0");
                 }
             }
         }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void ttunaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttunaiKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== 10){
            int total = Integer.parseInt(ttotal.getText());
            int bayar = Integer.parseInt(ttunai.getText());
            if (bayar<total){
                JOptionPane.showMessageDialog(this, "Jumlah Bayar Tidak Cukup");        
            }else{
                int kembali = bayar-total;
                tKembali.setText(Integer.toString(kembali));
            }
        }
    }//GEN-LAST:event_ttunaiKeyPressed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKurang;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnpilih;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btntambahbuku;
    private javax.swing.JTextField hargajual;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField judulbuku;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kdbuku;
    private javax.swing.JLabel nmbuku;
    private javax.swing.JTextField nmpembeli;
    private javax.swing.JTextField nonota;
    private javax.swing.JTextField tKembali;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTextField tatok;
    private javax.swing.JTextField ttotal;
    private javax.swing.JTextField ttunai;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
private DefaultTableModel model;
belicontrol bc = new belicontrol();
bukucontrol ob = new bukucontrol();
penjualancontrol pc = new penjualancontrol();

List<databeli> ListDb = new ArrayList<databeli>();
List<databuku> ListBuku = new ArrayList<databuku>();
List<datapenjualan> ListDPJ = new ArrayList<datapenjualan>();
}
